import type { NextPage } from 'next'
import Head from 'next/head'

import styled from 'styled-components'

const Red = styled.p`
  color: grey;
`

const Home: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>NOIE Architect</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className="text-center">NOIE Architect</h1>
        <Red className="text-center">Coming soon...</Red>
      </main>
    </div>
  )
}

export default Home
