import type { NextPage } from 'next'
import Head from 'next/head'

import styled from 'styled-components'

import Header from 'layouts/Header'
import Cover from 'components/Cover'
import Footer from 'layouts/Footer'

const Red = styled.p`
  color: grey;
`

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NOIE Architect</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;700&display=swap' />
      </Head>

      <main>
        <Header />
        <Cover />
        <Footer />
      </main>
    </div>
  )
}

export default Home
